StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{667B2E0B01C5BDEC}" {
   Id "ACE_Weather-AddonName"
   Target_en_us "ACE Weather"
   Target_ja_jp "ACE 天候"
   Target_ko_kr "ACE 날씨"
   Modified 1719367753
   Author "Kex"
   LastChanged "michy_REV19"
  }
  CustomStringTableItem "{66DA03F6906A98C5}" {
   Id "ACE_Weather-Item_Kacestrel4500_Description"
   Target_en_us "Pocket weather tracker"
   Target_de_de "Taschen-Wettermessgerät"
   Target_ja_jp "携帯用気象計"
   Target_ko_kr "휴대용 기상 관측기기"
   Target_zh_cn "口袋型氣象觀測儀"
   Modified 1730462104
   Author "Kexanone"
   LastChanged "michy_REV19"
  }
  CustomStringTableItem "{66DA03F69293ABD9}" {
   Id "ACE_Weather-Item_Kacestrel4500_Name"
   Target_en_us "Kacetrel 4500"
   Target_ja_jp "Kestrel 4500"
   Target_ko_kr "케ACE트렐 4500"
   Target_zh_cn "Kestrel 4500"
   Modified 1725566669
   Author "Kexanone"
   LastChanged "michy_REV19"
  }
  CustomStringTableItem "{667B2E0B3C32F8F7}" {
   Id "ACE_Weather-Keybind_WindInfoToggle"
   Target_en_us "Show wind info"
   Target_fr_fr "Afficher les informations sur le vent"
   Target_it_it "Mostra informazioni sul vento"
   Target_de_de "Zeige Windinformationen"
   Target_es_es "Mostrar información del viento"
   Target_cs_cz "Zobrazit údaje o větru"
   Target_pl_pl "Pokaż inf. o wietrze"
   Target_ru_ru "Показать информацию о ветре"
   Target_ja_jp "風情報を表示"
   Target_ko_kr "바람 정보 표시"
   Target_pt_br "Mostrar informação do vento"
   Target_zh_cn "顯示風力資訊"
   Target_uk_ua "Показати інформацію про вітер"
   Modified 1719368269
   Author "Kex"
   LastChanged "michy_REV19"
  }
 }
}