StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{670D1E431FCABE53}" {
   Id "ACE_Trenches-EditableEntity_PersonalTrench_01_big_Name"
   Target_en_us "Personal Trench (Big)"
   Target_de_de "Schützengraben (Groß)"
   Target_ja_jp "個人用塹壕（大）"
   Modified 1728932352
   Author "Kexanone"
   LastChanged "michy_REV19"
  }
  CustomStringTableItem "{670D4C2495CF93FE}" {
   Id "ACE_Trenches-EditableEntity_PersonalTrench_01_giant_Name"
   Target_en_us "Personal Trench (Giant)"
   Target_de_de "Schützengraben (Sehr Groß)"
   Target_ja_jp "個人用塹壕（特大）"
   Modified 1728932416
   Author "Kexanone"
   LastChanged "michy_REV19"
  }
  CustomStringTableItem "{670D1E4311B468FB}" {
   Id "ACE_Trenches-EditableEntity_PersonalTrench_01_small_Name"
   Target_en_us "Personal Trench (Small)"
   Target_de_de "Schützengraben (Klein)"
   Target_ja_jp "個人用塹壕（小）"
   Modified 1728932294
   Author "Kexanone"
   LastChanged "michy_REV19"
  }
  CustomStringTableItem "{670D1E4318FD977F}" {
   Id "ACE_Trenches-EditableEntity_TrenchSegment_01_short_Name"
   Target_en_us "Trench Segment (Short)"
   Target_de_de "Grabensegment (Kurz)"
   Target_ja_jp "塹壕区画（短）"
   Modified 1728932475
   Author "Kexanone"
   LastChanged "michy_REV19"
  }
  CustomStringTableItem "{670D6BA9CAA8072A}" {
   Id "ACE_Trenches-EditableEntity_VehicleTrench_01_Name"
   Target_en_us "Vehicle Trench"
   Target_de_de "Fahrzeug Schützengraben"
   Target_ja_jp "車両用塹壕"
   Modified 1728935966
   Author "Kexanone"
   LastChanged "michy_REV19"
  }
 }
}